{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s" (include "chart.name" $) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ include "chart.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if .Values.apis.files_service }}
          - path: /files
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s-svc" (include "chart.name" $) "files-service" }}
                port:
                  number: {{ .Values.apis.files_service.service.port }}
          {{- end }}
          {{- if .Values.apis.lightweight_service }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s-svc" (include "chart.name" $) "lightweight-service" }}
                port:
                  number: {{ .Values.apis.lightweight_service.service.port }}
          {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
