{{- range $key, $val := .Values.apis }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "chart.name" $) $key | kebabcase }}
  labels:
    app.kubernetes.io/name: {{ $key | kebabcase }}
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ include "chart.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}
    {{- with $val.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $val.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $val.replicas | default 1 }}
  {{- with $val.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $key | kebabcase }}
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $key | kebabcase }}
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/part-of: {{ include "chart.name" $ }}
        helm.sh/chart: {{ $.Chart.Name }}
        {{- with $val.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $val.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ $val.serviceAccount.name | default "default" }}
      {{- with $val.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $key | kebabcase }}
          {{- $image := get $val "image" | default dict }}
          image: "{{ get $image "registry" | default $.Values.global.image.registry }}/{{ get $image "repository" | default $.Values.global.image.repository }}:{{ get $image "tag" | default $.Values.global.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $val.imagePullPolicy | default "IfNotPresent" }}

          {{- with $val.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with $val.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with $val.env }}
          env:
            {{- range . }}
            - name:  {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}

          envFrom:
            - secretRef:
                name: {{ include "activeloop-neohorizon.fullname" $ }}
          {{- with $val.envFrom }}
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- if and $val.enableHealthProbes }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            failureThreshold: 20
            periodSeconds: 5
            timeoutSeconds: 3
          {{- end }}

          {{- with $val.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}


          {{- with $val.securityContext | default $.Values.global.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with $val.nodeSelector | default $.Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with $val.affinity | default $.Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with $val.tolerations | default $.Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with $val.podSecurityContext | default $.Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
